version: '3.5' # Definir versão atual
services: # Definir services
  angular-service: # Nome da service
    container_name: angularcontainer # Nome do container
    build: ./front-crud # Localicação DockerfileW
    volumes: # Volumes
    -  './front-crud:/usr/src/app'
    ports:
    -  '4200:4200' # Porta
    command: >
      bash -c "npm install && ng serve --host 0.0.0.0 --port 4200"